FROM denoland/deno:alpine AS build
WORKDIR /app
COPY . .
WORKDIR /app/web
RUN deno install --allow-scripts
WORKDIR /app/web/apps/www
RUN deno task build

FROM busybox:stable AS run
RUN adduser -D www
USER www
WORKDIR /home/www/app
COPY --from=build /app/web/apps/www/.vitepress/dist .
EXPOSE 5173
CMD ["busybox", "httpd", "-f", "-v", "-p", "5173"]