name: apple-devices
region: sfo

features:
  - buildpack-stack=ubuntu-22
  
alerts:
- rule: DEPLOYMENT_STARTED
- rule: DEPLOYMENT_LIVE
- rule: DEPLOYMENT_CANCELED
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
  disabled: true

domains:
  - domain: fuckingappledevices.com
    zone: fuckingappledevices.com
    type: PRIMARY
  - domain: api.fuckingappledevices.com
    zone: fuckingappledevices.com

ingress:
  rules:
    - component:
        name: frontend
      match:
        path:
          prefix: /
    - component:
        name: api
      match:
        path:
          prefix: /api

services:

  - name: frontend
    image:
      registry: $NAMESPACE # superepicstudios
      registry_type: $REGISTRY_TYPE # GHCR
      registry_credentials: "$REGISTRY_USER:$REGISTRY_TOKEN" # username:token
      repository: "$REPO-frontend" # apple-devices-frontend
      digest: $FRONTEND_DIGEST # sha256:...

  - name: api
    image:
      registry: $NAMESPACE
      registry_type: $REGISTRY_TYPE
      registry_credentials: "$REGISTRY_USER:$REGISTRY_TOKEN"
      repository: "$REPO-api" # apple-devices-api
      digest: $API_DIGEST
