name: apple-devices
region: sfo

features:
  - buildpack-stack=ubuntu-22
  
alerts:
- rule: DEPLOYMENT_STARTED
- rule: DEPLOYMENT_LIVE
- rule: DEPLOYMENT_CANCELED
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
  disabled: true

domains:
  - domain: fuckingappledevices.com
    zone: fuckingappledevices.com
    type: PRIMARY
  - domain: api.fuckingappledevices.com
    zone: fuckingappledevices.com

ingress:
  rules:
    - component:
        name: frontend
      match:
        path:
          prefix: /
    - component:
        name: api
      match:
        path:
          prefix: /api

services:

  - name: frontend
    image:
      registry_type: GHCR
      registry: ghcr.io
      registry_credentials: ${REGISTRY_USER}:${REGISTRY_TOKEN}
      repository: superepicstudios/apple-devices
      digest: ${FRONTEND_DIGEST}
    # health_check: TODO

  - name: api
    image:
      registry_type: GHCR
      registry: ghcr.io
      registry_credentials: ${REGISTRY_USER}:${REGISTRY_TOKEN}
      repository: superepicstudios/apple-devices
      digest: ${API_DIGEST}
    # health_check: TODO
