name: apple-devices
region: sfo

features:
  - buildpack-stack=ubuntu-22
  
alerts:
- rule: DEPLOYMENT_STARTED
- rule: DEPLOYMENT_LIVE
- rule: DEPLOYMENT_CANCELED
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
  disabled: true

services:

  - name: api
    image:
      registry_type: GHCR
      registry_credentials: ${REGISTRY_USER}:${REGISTRY_TOKEN}
      registry: superepicstudios
      repository: apple-devices
      digest: ${API_DIGEST}

  - name: frontend
    image:
      registry_type: GHCR
      registry_credentials: ${REGISTRY_USER}:${REGISTRY_TOKEN}
      registry: superepicstudios
      repository: apple-devices
      digest: ${FRONTEND_DIGEST}
