name: apple-devices
region: sfo

features:
  - buildpack-stack=ubuntu-22
  
alerts:
- rule: DEPLOYMENT_STARTED
- rule: DEPLOYMENT_LIVE
- rule: DEPLOYMENT_CANCELED
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
  disabled: true

domains:
  - domain: fuckingappledevices.com
    zone: fuckingappledevices.com
    type: PRIMARY
  - domain: www.fuckingappledevices.com
    type: ALIAS
    zone: fuckingappledevices.com
  - domain: api.fuckingappledevices.com
    zone: fuckingappledevices.com
    type: ALIAS

ingress:
  rules:
    - component:
        name: frontend
      match:
        path:
          prefix: /
    - component:
        name: api
      match:
        path:
          prefix: /api

services:

  - name: frontend
    image:
      registry: $NAMESPACE
      registry_type: $REGISTRY_TYPE
      registry_credentials: "$REGISTRY_USER:$REGISTRY_TOKEN"
      repository: "$REPO-frontend"
      digest: $FRONTEND_DIGEST
    http_port: 5173

  - name: api
    image:
      registry: $NAMESPACE
      registry_type: $REGISTRY_TYPE
      registry_credentials: "$REGISTRY_USER:$REGISTRY_TOKEN"
      repository: "$REPO-api"
      digest: $API_DIGEST
    http_port: 3000
