FROM denoland/deno:alpine AS build
WORKDIR /app
USER deno
COPY . .
RUN deno install --allow-scripts
RUN deno cache ./apps/api/src/main.ts

FROM denoland/deno:alpine AS run
WORKDIR /app
USER deno
COPY --from=build /app .
WORKDIR /app/apps/api
EXPOSE 3000
ENV NODE_ENV production
CMD ["deno", "task", "start"]
