FROM denoland/deno:alpine AS build
WORKDIR /app
COPY . .
RUN deno install --allow-scripts
USER deno
RUN deno cache ./apps/api/src/main.ts

FROM denoland/deno:alpine AS run
WORKDIR /app
COPY --from=build /app .
WORKDIR /app/apps/api
USER deno
ENV NODE_ENV production
EXPOSE 3000
CMD ["deno", "task", "start"]
